# arithmetic operations with arrays 

In [1]:
import numpy as np

In [3]:
a = np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
b = np.arange(11,20).reshape(3,3)
print(b)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [5]:
print(a+b)

[[12 14 16]
 [18 20 22]
 [24 26 28]]


In [6]:
print(b-a)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [7]:
print(a*b)

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


# generating random numbers 

In [10]:
x = np.random.randint(1,20,10) # from numpy library from random module import rand int function
print(x)

[ 3 19 17  6 10  5 13 17  3 11]


In [11]:
print(np.max(x))

19


In [12]:
print(np.min(x))

3


In [13]:
print(np.mean(x)) # sum of all elements in array / no of elements

10.4


In [14]:
print(np.median(x)) # 3 3 5 6 10 11 13 17 17 19 

10.5


In [15]:
print(np.argmax(x))

1


In [16]:
print(np.argmin(x))

0


# merging of arrays 

In [17]:
a = np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
b = np.arange(11,20).reshape(3,3)
print(b)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [19]:
m1 = np.concatenate((a,b))
print(m1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [20]:
m2 = np.concatenate((a,b),axis=1) # axis 1 means row axis = 0 means column
print(m2)

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [22]:
b1 = np.stack((a,b))
print(b1)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]


In [23]:
b2 = np.hstack((a,b))
print(b2)

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [24]:
b3 = np.vstack((a,b))
print(b3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [25]:
for i in b3:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]
[11 12 13]
[14 15 16]
[17 18 19]


In [27]:
for i in b3:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
11
12
13
14
15
16
17
18
19
