## creating arrays in different ways 

In [3]:
import numpy as np

In [5]:
list1 = [1,2,3]
print(type(list1))

<class 'list'>


## converting list into numpy array

In [6]:
arr1 = np.array(list1)
print(arr1)

[1 2 3]


In [7]:
## converting list into numpy array

In [8]:
t1 = (4,5,6)
arr2 = np.array(t1)
print(arr2)

[4 5 6]


In [9]:
print(type(arr2))

<class 'numpy.ndarray'>


In [10]:
## creating array using arange function

x = list(range(1,10))
print(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [11]:
arr3 = np.arange(10)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
y = list(range(1,100,2))
print(y)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]


In [15]:
arr4 = np.arange(1,100,2.5)
print(arr4)


[ 1.   3.5  6.   8.5 11.  13.5 16.  18.5 21.  23.5 26.  28.5 31.  33.5
 36.  38.5 41.  43.5 46.  48.5 51.  53.5 56.  58.5 61.  63.5 66.  68.5
 71.  73.5 76.  78.5 81.  83.5 86.  88.5 91.  93.5 96.  98.5]


In [16]:
arr5 = np.arange(2.5,100.5,2)
print(arr5)

[ 2.5  4.5  6.5  8.5 10.5 12.5 14.5 16.5 18.5 20.5 22.5 24.5 26.5 28.5
 30.5 32.5 34.5 36.5 38.5 40.5 42.5 44.5 46.5 48.5 50.5 52.5 54.5 56.5
 58.5 60.5 62.5 64.5 66.5 68.5 70.5 72.5 74.5 76.5 78.5 80.5 82.5 84.5
 86.5 88.5 90.5 92.5 94.5 96.5 98.5]


## creating array using linspace

In [19]:
arr6 = np.linspace(1,10,10,dtype=int)
print(arr6)

[ 1  2  3  4  5  6  7  8  9 10]


# predefined functions : ndim,shape,reshape

##  ndim: it is an attribute which is used to find the dimensions of an array
## shape: it is an atribute which is used to find shape of an array 
## reshape : it is an attribute which is used to change shape of a matrices 

In [21]:
a1 = np.array(10)
print(a1.ndim)

0


In [22]:
a2 = np.array([10,20,30])
print(a2.ndim)

1


In [23]:
a3 = np.array([[1,2,3],[4,5,6]])
print(a3)

[[1 2 3]
 [4 5 6]]


In [24]:
print(a3.ndim)

2


In [25]:
a3 = np.array([[1,2,3],[4,5,6]])
print(a3)

[[1 2 3]
 [4 5 6]]


In [26]:
print(a3.shape)

(2, 3)


In [33]:
a4 = np.arange(10).reshape((5,2))
print(a4)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
